name: Test
run-name: 'test: pulumi ${{ inputs.cmd }}'

on:
  workflow_dispatch:
    inputs:
      cmd:
        description: 'Pulumi command'
        required: true
        default: 'preview'
        type: choice
        options:
          - preview
          - up
          - refresh
          - destroy
          - init

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: read

jobs:
  pulumi:
    uses: ./.github/workflows/pulumi.yml
    with:
      cmd: ${{ inputs.cmd }}
      stack: test
      project: pulumi-v1-test
      working-directory: test
    secrets: inherit
